### ISSUE TITLE
Make olm optional

### ISSUE THREAD

**Issue by rumpelsepp** [tulir/mautrix-go#17]
Since the olm stuff depends on C libraries, it would be nice if the c dep could be disabled with build tags.

**Comment by tulir** [comment]
It already is optional: the crypto module isn't imported from any other module

**Comment by rumpelsepp** [comment]
Hmm, when I `go get -u` my project it complains:

```
$ go get -u ...
go: downloading maunium.net/go/mautrix v0.7.1-0.20200806170505-920619205aa2
# maunium.net/go/mautrix/crypto/olm
../../../go/pkg/mod/maunium.net/go/mautrix@v0.7.1-0.20200806170505-920619205aa2/crypto/olm/account.go:4:11: fatal error: olm/olm.h: No such file or directory
    4 | // #include <olm/olm.h>
      |           ^~~~~~~~~~~
compilation terminated
```

Any ideas? The code currently only does a login to a matrix server.

**Comment by tulir** [comment]
You probably shouldn't `...` there. Just `go build` or `go install` should work

**Comment by rumpelsepp** [comment]
Probably. That's how I update the go dependencies along my projects. But it seems to work a bit too recursive…
