### ISSUE TITLE
Concurrent map accesses when getting an intent or a client

### ISSUE THREAD

**Issue by babolivier** [tulir/mautrix-go#28]
It looks like several maps throughout intent/client related code paths aren't accessed in a concurrency-friendly way (according to the stack trace below and a quick skim through the code base), which can cause crashes due to races:

```
fatal error: concurrent map writes

goroutine 46766 [running]:
runtime.throw(0x9f2a0e, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000076b40 sp=0xc000076b10 pc=0x437c72
runtime.mapassign_faststr(0x94fa60, 0xc0001c1770, 0xc000618cc0, 0x3d, 0xc0006062d0)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc000076ba8 sp=0xc000076b40 pc=0x4163b1
maunium.net/go/mautrix/appservice.(*AppService).Client(0xc000104900, 0xc000618cc0, 0x3d, 0x2)
        /go/pkg/mod/maunium.net/go/mautrix@v0.7.6/appservice/appservice.go:170 +0x1f3 fp=0xc000076c18 sp=0xc000076ba8 pc=0x815033
maunium.net/go/mautrix/appservice.(*AppService).NewIntentAPI(0xc000104900, 0xc000618c01, 0x30, 0x1)
        /go/pkg/mod/maunium.net/go/mautrix@v0.7.6/appservice/intent.go:36 +0x155 fp=0xc000076cb0 sp=0xc000076c18 pc=0x817dd5
maunium.net/go/mautrix/appservice.(*AppService).Intent(0xc000104900, 0xc000618c00, 0x3d, 0xc000618c00)
        /go/pkg/mod/maunium.net/go/mautrix@v0.7.6/appservice/appservice.go:143 +0xf7 fp=0xc000076d18 sp=0xc000076cb0 pc=0x814c37
[...]
```

(the rest of the stack trace is omitted as it's application-specific and isn't relevant to mautrix-go)

Since the `EventProcessor`'s default mode is to start a new goroutine for each new event, it's quite easy to get in a situation in which two goroutine want to e.g. access an intent or a client in reaction to an incoming event.

**Comment by tulir** [comment]
Huh, I wonder why I never ran into that. The `intents` and `clients` caches in `AppService` are indeed not protected at all
