### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by r3k2** [tulir/mautrix-go#3]
looking for go libs to create a go bot for matrix but since most channels are encrypted I need it to support OLM for e2ee. does mautrix-go supports this? will it support it?

**Comment by tulir** [comment]
[gomuks](https://github.com/tulir/gomuks) will get e2ee from metaolm in some form (see tulir/gomuks#55). I might just make the integration in mautrix-go or at least a separate library that's easy to use with mautrix-go.
