### ISSUE TITLE
Call Events aren't parsed, leading to slightly confusing debug message

### ISSUE THREAD

**Issue by dbkr** [tulir/mautrix-go#32]
Whenever call events arrive, we get a log message like this:

```
DEBUG [2021-05-06T22:22:26.606378555Z] Failed to parse content of [$tFsRCPRjzbsPMfBBDPwtygFdo0PPa2rd67yKWZJdFYU m.call.hangup unsupported content type m.call.hangup (message)] (%!s(MISSING)): %!v(MISSING)
```

It looks like this is just because the Call events types aren't recognised as Message events in `GuessClass` - looks like the structures are all there so I guess the types just need to be added here?

Also I'm not sure where the %s(MISSING) stuff is coming from in the log line. For unknown event types, maybe something like, "Unknown message type <class>/<type>: not parsing" would be a better debug log?

**Comment by tulir** [comment]
`GuessClass` shouldn't be needed for parsing incoming events. The call structs were added recently (in v0.9.7), are you using a new enough version?

**Comment by dbkr** [comment]
Aha - I was not, sorry! That now gets further and have opened https://github.com/tulir/mautrix-go/issues/33
