### ISSUE TITLE
Getting id.RoomID by string

### ISSUE THREAD

**Issue by mikkel1156** [tulir/mautrix-go#9]
Don't know if I'm missing something, but I have the scenario where I have a config of the RoomIDs to check/send a message to (it might not be one that is joined yet). To interact with the rooms I need to pass an actual type of id.RoomID - which I'm unable to do since it isn't exported.

Can we get a simple function that could convert a string into a type of id.RoomID?

**Comment by tulir** [comment]
If you have something like a config struct that you parse JSON into, you can just use `id.RoomID` instead of `string` as the type there. Other than that, `id.RoomID` is just a string type, which means you can convert a string into one directly: `id.RoomID(yourString)`

**Comment by mikkel1156** [comment]
I cannot since it'll either say "undefined: id" or "cannot refer to unexported name mautrix.id" which is the problem, and why a function would be needed to get it from outside of the package.

**Comment by tulir** [comment]
That sounds like you need to import `maunium.net/go/mautrix/id`

**Comment by mikkel1156** [comment]
I see that I am indeed just an idiot.
